// <auto-generated />
using System;
using DocumentLifecycle.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentLifecycle.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260831131603_AddDocumentDomain")]
    partial class AddDocumentDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DocumentLifecycle.Domain.Activity.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("actor");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("details_json");

                    b.Property<Guid>("EntityPublicId")
                        .HasColumnType("char(36)")
                        .HasColumnName("entity_public_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("char(36)")
                        .HasColumnName("public_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("p_k_audit_events");

                    b.HasIndex("WorkspaceId", "OccurredAtUtc")
                        .HasDatabaseName("i_x_audit_events_workspace_id_occurred_at_utc");

                    b.HasIndex("WorkspaceId", "PublicId")
                        .IsUnique()
                        .HasDatabaseName("i_x_audit_events_workspace_id_public_id");

                    b.HasIndex("WorkspaceId", "EntityType", "EntityPublicId")
                        .HasDatabaseName("i_x_audit_events_workspace_id_entity_type_entity_public_id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("DocumentLifecycle.Domain.Documents.DocumentCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("char(36)")
                        .HasColumnName("public_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("p_k_document_categories");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_document_categories_workspace_id_name");

                    b.HasIndex("WorkspaceId", "PublicId")
                        .IsUnique()
                        .HasDatabaseName("i_x_document_categories_workspace_id_public_id");

                    b.ToTable("document_categories", (string)null);
                });

            modelBuilder.Entity("DocumentLifecycle.Domain.Documents.DocumentOwner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("contact");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("char(36)")
                        .HasColumnName("public_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("p_k_document_owners");

                    b.HasIndex("WorkspaceId", "DisplayName")
                        .IsUnique()
                        .HasDatabaseName("i_x_document_owners_workspace_id_display_name");

                    b.HasIndex("WorkspaceId", "PublicId")
                        .IsUnique()
                        .HasDatabaseName("i_x_document_owners_workspace_id_public_id");

                    b.ToTable("document_owners", (string)null);
                });

            modelBuilder.Entity("DocumentLifecycle.Domain.Documents.DocumentRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangeNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("change_note");

                    b.Property<long>("ManagedDocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("managed_document_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("media_type");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_filename");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("char(36)")
                        .HasColumnName("public_id");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int")
                        .HasColumnName("revision_number");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("sha256_hash")
                        .UseCollation("ascii_general_ci");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("StoredFilename")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("stored_filename");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("uploaded_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("p_k_document_revisions");

                    b.HasIndex("ManagedDocumentId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_document_revisions_managed_document_id_revision_number");

                    b.HasIndex("WorkspaceId", "PublicId")
                        .IsUnique()
                        .HasDatabaseName("i_x_document_revisions_workspace_id_public_id");

                    b.HasIndex("WorkspaceId", "StoredFilename")
                        .IsUnique()
                        .HasDatabaseName("i_x_document_revisions_workspace_id_stored_filename");

                    b.ToTable("document_revisions", (string)null);
                });

            modelBuilder.Entity("DocumentLifecycle.Domain.Documents.ManagedDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("archive_reason");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("archived_at_utc");

                    b.Property<string>("ArchivedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("archived_by");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("char(36)")
                        .HasColumnName("public_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("p_k_managed_documents");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("i_x_managed_documents_category_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("i_x_managed_documents_owner_id");

                    b.HasIndex("WorkspaceId", "CategoryId")
                        .HasDatabaseName("i_x_managed_documents_workspace_id_category_id");

                    b.HasIndex("WorkspaceId", "Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_managed_documents_workspace_id_code");

                    b.HasIndex("WorkspaceId", "ExpiryDate")
                        .HasDatabaseName("i_x_managed_documents_workspace_id_expiry_date");

                    b.HasIndex("WorkspaceId", "OwnerId")
                        .HasDatabaseName("i_x_managed_documents_workspace_id_owner_id");

                    b.HasIndex("WorkspaceId", "PublicId")
                        .IsUnique()
                        .HasDatabaseName("i_x_managed_documents_workspace_id_public_id");

                    b.HasIndex("WorkspaceId", "State")
                        .HasDatabaseName("i_x_managed_documents_workspace_id_state");

                    b.ToTable("managed_documents", (string)null);
                });

            modelBuilder.Entity("DocumentLifecycle.Domain.Notifications.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("deduplication_key");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("link");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("char(36)")
                        .HasColumnName("public_id");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("read_at_utc");

                    b.Property<string>("RecipientRole")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("recipient_role");

                    b.Property<string>("RecipientUserId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("recipient_user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.HasIndex("WorkspaceId", "DeduplicationKey")
                        .IsUnique()
                        .HasDatabaseName("i_x_notifications_workspace_id_deduplication_key");

                    b.HasIndex("WorkspaceId", "PublicId")
                        .IsUnique()
                        .HasDatabaseName("i_x_notifications_workspace_id_public_id");

                    b.HasIndex("WorkspaceId", "RecipientRole", "ReadAtUtc")
                        .HasDatabaseName("i_x_notifications_workspace_id_recipient_role_read_at_utc");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("DocumentLifecycle.Domain.Workspaces.DemoWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<int>("SeedVersion")
                        .HasColumnType("int")
                        .HasColumnName("seed_version");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("p_k_demo_workspaces");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("i_x_demo_workspaces_expires_at_utc");

                    b.ToTable("demo_workspaces", (string)null);
                });

            modelBuilder.Entity("DocumentLifecycle.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("user_name_index");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("role_name_index");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("p_k_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("p_k_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("p_k_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("DocumentLifecycle.Domain.Activity.AuditEvent", b =>
                {
                    b.HasOne("DocumentLifecycle.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_audit_events_demo_workspaces_workspace_id");
                });

            modelBuilder.Entity("DocumentLifecycle.Domain.Documents.DocumentCategory", b =>
                {
                    b.HasOne("DocumentLifecycle.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_document_categories_demo_workspaces_workspace_id");
                });

            modelBuilder.Entity("DocumentLifecycle.Domain.Documents.DocumentOwner", b =>
                {
                    b.HasOne("DocumentLifecycle.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_document_owners_demo_workspaces_workspace_id");
                });

            modelBuilder.Entity("DocumentLifecycle.Domain.Documents.DocumentRevision", b =>
                {
                    b.HasOne("DocumentLifecycle.Domain.Documents.ManagedDocument", null)
                        .WithMany("Revisions")
                        .HasForeignKey("ManagedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_document_revisions_managed_documents_managed_document_id");
                });

            modelBuilder.Entity("DocumentLifecycle.Domain.Documents.ManagedDocument", b =>
                {
                    b.HasOne("DocumentLifecycle.Domain.Documents.DocumentCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_managed_documents_document_categories_category_id");

                    b.HasOne("DocumentLifecycle.Domain.Documents.DocumentOwner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_managed_documents_document_owners_owner_id");

                    b.HasOne("DocumentLifecycle.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_managed_documents_demo_workspaces_workspace_id");

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DocumentLifecycle.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("DocumentLifecycle.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_notifications_demo_workspaces_workspace_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DocumentLifecycle.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DocumentLifecycle.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("DocumentLifecycle.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DocumentLifecycle.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("DocumentLifecycle.Domain.Documents.ManagedDocument", b =>
                {
                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
