<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\DocumentLifecycle.Application\DocumentLifecycle.Application.csproj" />
    <ProjectReference Include="..\DocumentLifecycle.Infrastructure\DocumentLifecycle.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <UserSecretsId>DocumentLifecycle.Web-Portfolio-2026</UserSecretsId>
    <FrontendRoot>$(MSBuildProjectDirectory)\..\..\</FrontendRoot>
  </PropertyGroup>

  <Target Name="BuildFrontendAssets" BeforeTargets="PrepareForBuild" Condition="'$(DesignTimeBuild)' != 'true'">
    <Exec WorkingDirectory="$(FrontendRoot)" Command="npm run build:assets" />
  </Target>

</Project>
